apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T08:54:48Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3693"
  uid: 6339bb1d-5c9f-4823-8471-c03b7ddf84b3
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.123.113
  clusterIPs:
  - 10.103.123.113
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30511
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
